### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by PragTob** [devinus/poison#105]
Hi there,

thanks a lot for Poison! 

It'd be great to have a CHANGELOG though, so especially that with a new major version like now one could check out the changes and see what, if anything was breaking :)

Thanks + cheers,
Tobi

**Comment by benwilson512** [comment]
Seconding this. As a library author with packages that depend on Poison I honestly don't know what constraint to put. Everything seems to work at all the versions, but `"~> 1"` seems a bit promiscuous.

**Comment by johnhamelink** [comment]
I really wish a changelog would be implemented, or at least a guide on what's changed between 2.x and 3.x 😞

**Comment by quolpr** [comment]
Poison really miss changelog :( I can't just upgrade to 4.0 cause I am not sure what things were really changed

**Comment by fenollp** [comment]
https://github.com/devinus/poison/compare/3.1.0...master
Doesn't seem too dangerous.

**Comment by benwilson512** [comment]
Everyone should just move to Jason at this point really.

**Comment by PragTob** [comment]
I think the only hold back at this point is that the new phoenix version with jason still isn't out although it's been on master for ~7 months I think

**Comment by epinault** [comment]
any chance we can get a changelog?  no idea what is in 5.0 but that s very difficult to want to upgrade in the wild

**Comment by esambo** [comment]
Please add a changelog to allow the users of this library to reason about major versions, and what kind of breaking changes it may introduce. Or create [releases](https://github.com/devinus/poison/releases) for your [tags](https://github.com/devinus/poison/tags), e.g. https://github.com/elixir-tesla/tesla/releases/tag/v1.5.0

**Comment by epinault** [comment]
I think this project is dead because no MR have been merged since 2021 and many other MR waiting or bugs since then that are not being looked at . @devinus  any chance  you could share ownership or add more people. I am sure some of us would love to contribute but someone needs the keys
