### ISSUE TITLE
Poison.encode! vulnerability

### ISSUE THREAD

**Issue by rstacruz** [devinus/poison#108]
There are certain *valid* inputs that will cause `Poison.encode!(input)` to throw an error.

I can give some examples but I'd rather not do so here—I've noticed one Elixir web app that has web servers crash because of this.

Let me email you some examples and details @devinus :)

**Comment by ericmj** [comment]
Why is this a vulnerability?

**Comment by imranismail** [comment]
I thought encode with a bang is suppose to crash if Poison can't encode the input?

**Comment by ivan** [comment]
Maybe it's time to disclose this one?  If there is JSON-encodable input that makes `encode!` throw, it would be good to know so that I can either work around it or fix it.

**Comment by devinus** [comment]
Not a vulnerability, but this behaviour has been changed in https://github.com/devinus/poison/commit/a4208a6252f4e58fbcc8d9fd2f4f64c99e974cc8.

**Comment by rstacruz** [comment]
For sake of disclosure, it was:

```elixir
Poison.encode!("\x80\x20")
```

It caused a vulnerability in our app because we used `Poison.encode!` on user input (that we sanitized to ensure it was a valid utf8 and latin1 string).
