### ISSUE TITLE
The most correct way to read a JSON file.

### ISSUE THREAD

**Issue by lk-geimfari** [devinus/poison#121]
What is most correct way to open (read) and parse JSON file with `poison`?

For example if we have `example.json` file in root of some project.

```elixir
def get_json(filename) do
    # ....
end
```

**Comment by lucidstack** [comment]
This is fairly straight-forward, @lk-geimfari. Here's a little snippet:
```
def get_json(filename) do
  filename
  |> File.read!
  |> Poison.decode!
end
```
Warning: this function will throw an error if the file can't be read, or if Poison can't decode its content (notice the `!` on the function names). For a safer alternative:
```
def get_json(filename) do
  with {:ok, file_content} <- File.read(filename) do
    Poison.decode(file_content)
  end
end
```
this will either return `{:ok, json}` from `Poison.decode`, `{:error, reason}` from `File.read` (look up `with` if you are unfamiliar with it, or `{:error,  :invalid}` from `Poison.decode`, in case the JSON can't be decoded into Elixir (well, Erlang, technically) terms.

Hope this helps! 😀 👋

**Comment by lk-geimfari** [comment]
@lucidstack Thank you! It's look really nice.
