### ISSUE TITLE
Unexpected 3 tuple return when supplying an invalid string to Poison.decode/1

### ISSUE THREAD

**Issue by binarylogic** [devinus/poison#122]
This has tripped us up multiple times. We're also noticing it in other libraries (https://github.com/garyf/json_web_token_ex/issues/16).

```elixir
iex(1)> Poison.decode("")
{:error, :invalid, 0}
```

The `@spec` for `Poison.decode/1` does not specify this type of return. It appears the return should be: https://github.com/devinus/poison/blob/2d696bd8dc61ef2ac0787f738076c889baccd959/lib/poison.ex#L67

```elixir
iex(1)> Poison.decode("")
{:error, {:invalid, 0}}
```

Is the former or the later correct? Thanks!

**Comment by devinus** [comment]
This behaviour has been changed in https://github.com/devinus/poison/commit/a4208a6252f4e58fbcc8d9fd2f4f64c99e974cc8. All non-bang functions return a 2-tuple, `{:ok, value}` or `{:error, exception :: struct()}`.

**Comment by ffleming** [comment]
Could a release be cut that incorporates this change?
