### ISSUE TITLE
Error format doesn't match the docs

### ISSUE THREAD

**Issue by ntrepid8** [devinus/poison#127]
Sometimes when attempting to decode invalid JSON with the version 3.1 I see this sort of return value:
```
{:error, :invalid, 0}
```

The docs seem to indicate that the error tuples should be one of these:
```
{:error, :invalid}
{:error, {:invalid, String.t}}
```

I think this line is the culprit:
- https://github.com/devinus/poison/blob/master/lib/poison/parser.ex#L54

I think it was from this PR:
- https://github.com/devinus/poison/pull/100

@devinus would you accept a PR to change the error tuple from this:
```
{:error, :invalid, 0}
```
to this?
```
{:error, {:invalid, 0}}
```

I would also update the docs to include this as a possible error tuple to indicate the position:
```
{:error, {:invalid, integer}}
```

**Comment by devinus** [comment]
This behaviour has been changed in https://github.com/devinus/poison/commit/a4208a6252f4e58fbcc8d9fd2f4f64c99e974cc8.
