### ISSUE TITLE
please give some  Record   use case

### ISSUE THREAD

**Issue by zhaohansprt** [devinus/poison#130]
I used  such  code below to  define Record in  a module     
```
require Record
 Record.defrecord :momentUser, [:Uid, :Ctype, :Cid]
```

and  seems not  work  with   

> Poison.decode!(j, as: %momentUser{})
  or
> Poison.decode!(j, as: :momentUser)

in the  same module

**Comment by devinus** [comment]
Poison doesn't deal with records, you want a struct.
