### ISSUE TITLE
decode throws on invalid input

### ISSUE THREAD

**Issue by karlseguin** [devinus/poison#132]
A fuzz tester found some input that caused Poison.decode to throw. Maybe this is an expected behavior on invalid input, but I'm under the impression only decode! should fail in such a way.

I'm unfortunately not sure what the full input was (I can let it run again until it happens if necessary), but `:erlang, :binary_to_integer, [<<68, 16, 5, 5>>, 16], []}` ended up being called from parser's string_escape function: https://github.com/devinus/poison/blob/master/lib/poison/parser.ex#L250

**Comment by devinus** [comment]
This behaviour changed in https://github.com/devinus/poison/commit/a4208a6252f4e58fbcc8d9fd2f4f64c99e974cc8.
