### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by asummers** [devinus/poison#133]
I'm getting an error parsing JSON using Poison 3.1.0. I've narrowed the offending JSON to:

```
{
  "color": "\"#2471A3\""
}
```

This validates, according to https://jsonlint.com/ and https://jsonformatter.curiousconcept.com/ but I get the following stack trace when decoding it.

```
iex(1)> json = """
...(1)> {
...(1)>   "color": "\"#2471A3\""
...(1)> } 
...(1)> """
"{\n  \"color\": \"\"#2471A3\"\"\n}\n"
iex(2)> Poison.decode!(json)
** (Poison.SyntaxError) Unexpected token at position 15: #
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
```
Replacing the `#` with `%23` results in Poison then complaining about an unexpected `%` token in the same fashion.

**Comment by devinus** [comment]
@asummers `IO.puts` your `json` variable and you'll see what's wrong.
