### ISSUE TITLE
Version 4.0 not on Hex, only 3.1.0 there

### ISSUE THREAD

**Issue by slebaillif** [devinus/poison#134]

**Comment by ericmj** [comment]
Seems like version 4.0 is not on github either so it's probably not released yet :)

**Comment by ericmj** [comment]
Many people are getting confused by this. Can we change this back to the released version until 4.0 is released? /cc @devinus

**Comment by devinus** [comment]
@ericmj Good point. Should I set it to `4.0.0-dev` perhaps? I have one more thing to do before release, so I need to wait a few more days still.

**Comment by devinus** [comment]
Ah, I just realized I did set it to `4.0.0-dev`. Why do you think people are having problems?

**Comment by ericmj** [comment]
I think it's mainly the installation instructions in the README that are confusing people https://github.com/devinus/poison#installation. Even though the master branch is 4.0.0-dev maybe we can have the readme point to stable since the readme is the first thing most people see.

**Comment by yordis** [comment]
@devinus I would say to create some `develop` branch so people will never see inconsistency on the `master` branch with what they have installed from Hex.

I know that at the end of the day we have to pay attention but I think that practices like this one would help a lot. Specially when the people click on the Github link on Hex and they could miss the point that the README of the `master` branch is not necessary the Hex version unless they check the `mix` version.

What do you think?

**Comment by devinus** [comment]
v4.0.0 published on Hex: https://hex.pm/packages/poison/4.0.0
