### ISSUE TITLE
Custom Decoder or Equivalent

### ISSUE THREAD

**Issue by tuxagon** [devinus/poison#139]
This is probably more of a question than an issue. Essentially what I would like to do is take a JSON array and decode each item based on a `type` field that every item is guaranteed to have. So, I have several structs
```
defmodule A do
    defstruct [:name, :type, :a_field]
end

defmodule B do
    defstruct [:type, :b_field]
end
```
and I would like to decode my JSON into either `A` or `B` based on the field `type`. My thought is to use a custom decoder that will take just a map
```
defimpl Poison.Decoder, for: Map do
    def decode(%{type: type}, options) do
        # Choose type
    end
end
```
The decode code is more guessing than expectation. How could I accomplish this with `poison`?

**Comment by tuxagon** [comment]
I came up with an different solution to this problem which does not actually need a custom decoder. Closing.

**Comment by sunny-g** [comment]
@tuxagon I know its been a while, but can you share how you avoided needing to implement your own `Decoder`?

**Comment by tuxagon** [comment]
@sunny-g 😞 it has been so long, I don't even remember the project this would've been for right now. I'm trying to think back to the problem, though, and it's possible that I leveraged pattern matching with tuples like `{:a, A}`. I'm sorry I couldn't be more help here 😅
