### ISSUE TITLE
Incorrect typespecs/docs for Posion.decode/2 and Parser.parse/2

### ISSUE THREAD

**Issue by mgartner** [devinus/poison#142]
Version: 3.1.0

It looks like `{:error, :invalid, integer}` is a valid return type for both `Poison.decode/2` and `Parser.parser/2`, but neither type spec reflects this.

Here is where a tuple of that type is possibly returned:
* https://github.com/devinus/poison/blob/3.1.0/lib/poison/parser.ex#L44

Notice the typespecs of `Poison.decode/2` and `Parser.parser/2` do not include this type:
* https://github.com/devinus/poison/blob/3.1.0/lib/poison/parser.ex#L32-L33
* https://github.com/devinus/poison/blob/3.1.0/lib/poison.ex#L66-L67

I noticed this when `{:error, :invalid, 0}` was returned by `Poison.decode/2` in our production app.

**Comment by ConnorRigby** [comment]
I've also noticed this. Any word?

**Comment by devinus** [comment]
Changed in 5.0.
