### ISSUE TITLE
Inspect.BitString.escape no longer exists

### ISSUE THREAD

**Issue by ivan** [devinus/poison#143]
https://github.com/elixir-lang/elixir/commit/0b0ab9f8ef420ea07878e3156386ddad10bb3ea8#diff-6fd830f891dc229cc43bbeb19b95acd9L119 broke poison@master because it removed `Inspect.BitString.escape`:

```
==> poison
Compiling 4 files (.ex)
warning: function Inspect.BitString.escape/2 is undefined or private
  lib/poison/parser.ex:20
```

**Comment by devinus** [comment]
Fixed in v4.0.0.
