### ISSUE TITLE
Tag latest master and push to hex.pm

### ISSUE THREAD

**Issue by mrinalwadhwa** [devinus/poison#148]
The latest master has fixes, especially the fix to Elixir 1.5 warnings 
https://github.com/devinus/poison/commit/a4208a6252f4e58fbcc8d9fd2f4f64c99e974cc8

It would be nice if that could get a tag (`3.2.0`?) and pushed to hex.pm.

**Comment by mariusbutuc** [comment]
```
warning: String.strip/1 is deprecated, use String.trim/1
  ~/app/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  lib/poison/encoder.ex:173
```

Have been fixed for a while now. Sounds like bumping the patch version would be appreciated.

**Comment by mariusbutuc** [comment]
Also, is there some overlap between this issue and #134?

**Comment by redink** [comment]
Any update?

**Comment by ivan** [comment]
FWIW: Poison master is incompatible with Phoenix because `Poison.encode_to_iodata!` is gone.

**Comment by devinus** [comment]
v4.0.0 published on Hex: https://hex.pm/packages/poison/4.0.0
