### ISSUE TITLE
Issue with german umlauts/UTF-8?

### ISSUE THREAD

**Issue by loyaruarutoitsu** [devinus/poison#155]
Hello,

I was using Poison to Decode a JSON Schema which contained German Umlauts, letters like öäüÖÄÜß.

The statement was:
`
schema = Poison.decode! '{"type": "object", "properties": { "foo": {"type": "string", "example": "öäü"}}}'
`

And I got this error:
`
** (Poison.SyntaxError) Unexpected end of input at position 73
    (poison) lib/poison/parser.ex:55: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
`

Could you please tell me what I'm doing wrong?

**Comment by vorce** [comment]
Try this instead:
`Poison.decode! "{\"type\": \"object\", \"properties\": { \"foo\": {\"type\": \"string\", \"example\": \"öäü\"}}}"`

Single quotes denotes a charlist (a charlist contains the code points of the characters between single-quotes), while double quotes means string (a UTF-8 encoded binary). More info here: https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html
