### ISSUE TITLE
Deprecation warnings on 1.6

### ISSUE THREAD

**Issue by halfdan** [devinus/poison#161]
We're running elixir with warnings as errors and on Elixir 1.6 we're getting:

```
warning: String.strip/1 is deprecated, use String.trim/1
  [..]/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  lib/poison/encoder.ex:173
```

This seems to be fixed on master but no release has been cut since 3.1.0 where both are still present. Do you mind cutting a new release with those two warnings fixed?

**Comment by devinus** [comment]
Fixed in v4.0.0.
