### ISSUE TITLE
Is this library being maintained?

### ISSUE THREAD

**Issue by tanweerdev** [devinus/poison#167]
I see no release after `Jan 15, 2017` and many issues open for a very long time and many pull requests not merged. Is this library even being maintained?

**Comment by furqanaziz** [comment]
Maintainers are having a hard time maintaining this library. Contributors are much appreciated to fix issues and keep opening PRs so that we can keep this library up for the community.

**Comment by devinus** [comment]
v4.0.0 has been published on Hex.
