### ISSUE TITLE
Poison.encode_to_iodata!/1 missing in 4.x 

### ISSUE THREAD

**Issue by smeevil** [devinus/poison#172]
I was wondering what happend to the Poison.encode_to_iodata!/1 function and why it seems to have been removed ? (Also a CHANGELOG.md would help ;))

This function is used by  lib/phoenix/controller.ex:342
```elixir
 defp encode(content, template) do
    if encoder = Template.format_encoder(template) do
      encoder.encode_to_iodata!(content)
    else
      content
    end
  end
```

**Comment by slashdotdash** [comment]
The recently release Postgrex v0.14.0 expects the [JSON encoder to provide an `encode_to_iodata!/1` function]https://github.com/elixir-ecto/postgrex/issues/282. Since this has been removed from Poison, it means that Poison cannot be used with Postgrex.

**Comment by Qqwy** [comment]
This is still important!

**Comment by MeerKatDev** [comment]
This happens also with the new myxql driver
