### ISSUE TITLE
How to use Poison.decode(data, as: %SomeStruct{}) in combination with @required_fields?

### ISSUE THREAD

**Issue by Qqwy** [devinus/poison#179]
A bit of a chicken-and-egg problem, maybe, but: 

```

defmodule Foo do
  @required_fields [:id, :name]
  defstruct [:id, :name, slogan: "Hello, world!"]
  
  def parse(json) do
    # XXXXX
  end
end
```

What to enter in the location of the `# XXXX`?

- `Poison.decode(data, as: %Foo{})` will not work, as the `%Foo{}` is rejected by the Elixir compiler.
- `Poison.decode(data, as: Foo)` will not work, because Poison only works with structs, not with modules-representing-structs.

How to do this? Maybe it's possible that the second approach is added to Poison?

**Comment by iilyak** [comment]
I am having the same issue. I think I found the workaround
```
def parse(json) do
  Poison.decode(json, as: __MODULE__.__struct__)
end
```

**Comment by halimnadergrace** [comment]
- [rcs]()
