### ISSUE TITLE
Encoding a map changes the order of the keys

### ISSUE THREAD

**Issue by sideshow** [devinus/poison#21]
Encoding a map changes the order of the keys;

``` elixir
iex(6)> Poison.encode %{a: 1, b: 2, c: 3}
{:ok, "{\"c\":3,\"b\":2,\"a\":1}"} # reversed keys
```

Similarly decoding json changes the order of the keys;

``` elixir
iex(7)> Poison.decode "{\"c\":3,\"b\":2,\"a\":1}", keys: :atoms!
{:ok, %{a: 1, b: 2, c: 3}} # reversed keys
```

**Comment by dvv** [comment]
Still, by substituting `foldl`with `foldr`at both https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L249 and https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L255 solves reversal of keys while encoding.
Is such PR welcome?

**Comment by alvesl** [comment]
> @sideshow A map's keys are unordered. 
That makes sense, but I also have a strong use case for this, whenever encoding JSON that will be sent to AWS firehose they expect it in a certain order.
Maybe extending the lib to work with keywords?
