### ISSUE TITLE
Poison 5.0 fails to decode Unicode surrogate pairs, Poison 4.0.1 succeeds

### ISSUE THREAD

**Issue by adworse** [devinus/poison#217]
Reproduction:

```elixir 
Poison.decode!("{\"description\":\"\\uD83D\\uDD32\\uD83D\\uDD34\\uD83D\\uDD33\"}")
```

**Comment by wisq** [comment]
Yeah, running into this as well.

Poison 5.0:
```
iex(1)> ~S{"\ud83d\udc69\ud83c\udffd\u200d\ud83d\udcbb"} |> Poison.decode()
{:error,
 %Poison.ParseError{
   data: "\"\\ud83d\\udc69\\ud83c\\udffd\\u200d\\ud83d\\udcbb\"",
   skip: 32,
   value: "\\ud83d"
 }}
 ```
 
Poison 4.0.1:
```
iex(1)> ~S{"\ud83d\udc69\ud83c\udffd\u200d\ud83d\udcbb"} |> Poison.decode()
{:ok, "👩🏽‍💻"}
```

**Comment by irisTa56** [comment]
It seems related to a zero-width joiner between two surrogate pairs.
Note that I could reproduce @wisq's example, but couldn't reproduce @adworse's example.

Shorter examples I tried on Poison 5.0.0:

```elixir
# with a zero-width joiner
iex(1)> Poison.decode(~S("\uD83D\uDC68\u200D\uD83D\uDC76"))
{:error,
 %Poison.ParseError{
   data: "\"\\uD83D\\uDC68\\u200D\\uD83D\\uDC76\"",
   skip: 20,
   value: "\\uD83D"
 }}
# without a zero-width joiner
iex(2)> Poison.decode(~S("\uD83D\uDC68\uD83D\uDC76"))
{:ok, "👨👶"}
# with a zero-width joiner but the following character is not a surrogate pair
iex(3)> Poison.decode(~S("\uD83D\uDC6E\u200D\u2642"))
{:ok, "👮‍♂"}
```

**Comment by devinus** [comment]
All of these examples fail in the browser using `JSON.parse` other than the @adworse's original example which Poison 5.0 also correctly parses.

Poison 5.0 passes all spec tests, so I'm wary of allowing strings to parse that wont parse in a browser environment.

**Comment by wisq** [comment]
Both Firefox and Chrome seem fine with my example.
<img width="489" alt="Screenshot 2024-03-05 at 18 30 19" src="https://github.com/devinus/poison/assets/255758/30ad0646-aa3c-474b-b1e8-adc50cd2fa9a">
<img width="476" alt="Screenshot 2024-03-05 at 18 30 50" src="https://github.com/devinus/poison/assets/255758/3d100f28-3153-4e44-b68e-14ca334e7ddc">

**Comment by devinus** [comment]
@wisq You're right, I must have somehow tested them wrong. Investigating this and @irisTa56's solution.
