### ISSUE TITLE
Adding README.md examples as Parser Tests

### ISSUE THREAD

**Issue by vendethiel** [devinus/poison#24]
Hi!

I was looking for a schema-validating library for elixir, and yours seems to best shaped to do what I what.

However, trying to get more out of the `as:` option, I went straight to the tests and noticed that the examples in the README.md aren't in the test suite. I really think they should be (if you want me to, I can PR for that, but obviously it's your code).

I'm also wondering another thing: what's the limit of the "as" syntax? Say, for example, that I have a top-level array containing objects (that I want to be structs), how should I go around doing that?

This is my current code:

```elixir
defmodule Parent
  defstruct [:name, :children]
end

defmodule Child
  defstruct [:name]
end

Poison.decode!(
  ~s([{“name”: “a”, “children”: [{“name”: “child1”}]}, {“name”: “b”, “children": []}],
  as: ??)
```

**Comment by devinus** [comment]
The example code I use in the `README` are almost the same as the test code.

`decode(person, as: [Person])` would be how you handle decoding an array of objects into structs.

**Comment by vendethiel** [comment]
Thanks. That doesn't seem to explicite how it should work for **nested** objects (as in my example), though, right?
