### ISSUE TITLE
jiffy gets included as a dependency in the project

### ISSUE THREAD

**Issue by HashNuke** [devinus/poison#25]
When Poison is added to a project, the project's mix.lock file contains jiffy as a dependency. I'm guessing this is for benchmarking only and shouldn't be there.

**Comment by ericmj** [comment]
This shouldn't be happening. What Elixir version are you using? Can you also show the mixfile you have?

**Comment by HashNuke** [comment]
@ericmj private work repo with a spider-web of dependencies, but I think @devinus still has access to the repo (we shared the same workplace).

So the project A, depends on library B, which includes poison as a dependency. I'll try and reproduce this in a separate app and post an update here.

**Comment by ericmj** [comment]
My guess is that another dependency is adding jiffy. It's not a bug in poison at least.

**Comment by devinus** [comment]
@HashNuke cberl is requiring jiffy.

**Comment by HashNuke** [comment]
@devinus Thanks for clarifying. Didn't notice that (grep returned poison's mix.exs and I thought the on: :bench thing wasn't working right).

Closing this issue.
