### ISSUE TITLE
Error when using with `keys: :atoms!` and the atom hasn't yet existed

### ISSUE THREAD

**Issue by cmpitg** [devinus/poison#27]
With Poison `master` and release 1.3.1, this happens:

```
iex(3)> Poison.decode ~s({"what": "where"}), keys: :atoms!
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("what", :utf8)
    lib/poison/parser.ex:97: Poison.Parser.object_name/2
    lib/poison/parser.ex:82: Poison.Parser.object_pairs/3
    lib/poison/parser.ex:36: Poison.Parser.parse/2
    lib/poison.ex:69: Poison.decode/2
iex(3)> :what
:what
iex(4)> Poison.decode ~s({"what": "where"}), keys: :atoms!
{:ok, %{what: "where"}}
```

I'm using Elixir 1.0.2 and Erlang/OTP 17.

**Comment by cmpitg** [comment]
I've just browsed through the source code. It turns out that I should use `:atoms` instead of `:atoms!`. Should this be noted in README file, it'd be very helpful to avoid early confusion.

**Comment by devinus** [comment]
@cmpitg It is very dangerous to use `:atoms:`, so please decode your keys into strings unless you absolutely know what you're doing.

**Comment by devinus** [comment]
I would only ever use `:atoms` during testing or when consuming my own endpoint, and even then I'd be wary. See also: Erlang atom exhaustion.

**Comment by cmpitg** [comment]
@devinus Thanks for the heads-up. I forgot about the exhaustion thing. My case was a bit different as the map I wanted to output has a fixed set of keys. Perhaps a better design would be a struct and the `as:` option. Anyway, what do you think about having a small note on `:atoms` vs. `:atoms!` and Erlang atom allocation in README?

**Comment by devinus** [comment]
@cmpitg Create a PR and I will accept.
