### ISSUE TITLE
Big Ints

### ISSUE THREAD

**Issue by vishnevskiy** [devinus/poison#30]
I was wondering if you have any suggestion how to handle BigInts or the best way to go about it since JavaScript will truncate the number.

In my internal code I did this.

```elixir
defimpl Poison.Encoder, for: Integer do
  def encode(integer, options) when integer > 9007199254740992 do
    if options[:bigint_as_string] do
      ~w("#{integer}")
    else
      Integer.to_string(integer)
    end
  end

  def encode(integer, _options) do
    Integer.to_string(integer)
  end
end

```

Which the linter hates but it does work. I am assuming the Erlang compiler optimizes this to not hit the keyword lookup if the number is small.

It might be nice to have an option similar to Python's simplejson `bigint_as_string`

http://simplejson.readthedocs.org/en/latest/#basic-usage

**Comment by devinus** [comment]
The JSON spec doesn't limit number size, and `9007199254740992` is JavaScript specific, so I would name the option e.g. `javascript: true | false`. I would be willing to accept a PR for this.
