### ISSUE TITLE
Is this library still considered "experimental"?

### ISSUE THREAD

**Issue by SteveAquino** [devinus/poison#31]
I've noticed that this library is past version 1.0 yet the description still says this project is "experimental'.  I'm just curious if that is still true or if this library should be considered useable for production applications.  If the latter we should probably update that description :smile:.

![screen shot 2015-03-31 at 4 27 31 pm](https://cloud.githubusercontent.com/assets/539839/6931517/fb96b186-d7c2-11e4-9244-3e7518879703.png)

**Comment by devinus** [comment]
Fixed.
