### ISSUE TITLE
nested struct decoding

### ISSUE THREAD

**Issue by jschoch** [devinus/poison#32]
example code here: https://gist.github.com/jschoch/b9c4f9c08fa5be127c67

The example is a bit of a hack and i'm wondering why this isn't a feature, assuming there is some reason.

Goal is to be able to run the decoder on nested structs.

%Foo{tuple: {1,2}} encodes it's to [1,2] and decodes to {1,2}

encode/decode should work on the below and have the :tuple converted to a list and back

%Bar{name: :baz, foo: %Foo{ tuple: {1,2}}

**Comment by padde** [comment]
This would be really nice. We've discussed a similar case in this SO question: http://stackoverflow.com/questions/30855638/elixir-nested-json-parsing-to-structs

Given this JSON:

    json = {"name": "blah blah", "address": {"street": "smthing"}}

it would be nice to be able to write

    Poison.decode!(json, as: %User{address: Address})

I could probably look into that by the end of this week if you like.

**Comment by devinus** [comment]
Currently working on an implementation of this. Will be part of Poison 2.0. Updates coming this weekend.

**Comment by padde** [comment]
@devinus thanks for your work, really looking forward to this!

**Comment by JoelPM** [comment]
Looking forward to this as well. Will the forthcoming implementation support arbitrary levels of nesting and multiple sub struct type definitions? For example:

Poison.decode!(json, as: %User{ address: %Address{}, creds: %Creds{ foo: %Bar{} } })

**Comment by devinus** [comment]
@JoelPM Yes, you should be able to nest as much as you want. Still working on the implementation.

**Comment by stevedomin** [comment]
@devinus do you have an ETA on this? (not trying to be pushy at all, I'm just curious)

**Comment by devinus** [comment]
@stevedomin This is being worked on. It's really hard to get it right. Hopefully this weekend I'll be able to finish it.

**Comment by leifg** [comment]
Been playing around with Poison, it would truly be an awesome feature.

**Comment by stevedomin** [comment]
@devinus have you made any progress on that one? If you are too busy I'm happy to take a look at it (some pointers would be great though)

**Comment by rcoedo** [comment]
I would love to have this feature!

**Comment by ffloyd** [comment]
+1

**Comment by lilfaf** [comment]
+1

**Comment by Foo42** [comment]
I take it this is trickier than it first seemed to implement. It would definitely be useful!

**Comment by arunpoudel** [comment]
+1

**Comment by devinus** [comment]
An update for everybody watching this: this is still a very hard problem, but I'm going to tackle it this weekend. Keep posted or ping me if I forget to update everybody.

**Comment by stevedomin** [comment]
That's awesome @devinus, looking forward to your update!

**Comment by devinus** [comment]
Hey guys, will be providing an update on this tomorrow.

**Comment by rcoedo** [comment]
@devinus Thanks for your dedication! :smiley:

**Comment by devinus** [comment]
Should finish it up by tomorrow: https://github.com/devinus/poison/pull/58

Considering making this a semver major breaking API change.

`Poison.decode!(json, as: Person)` will no longer work. Use `Poison.decode!(json, as: %Person{})`

The reason for this is you can't do `Poison.decode!(json, as: %Person{address: Address})` for reasons like dialyzer. I don't want to confuse people, and if I keep the `as: Person` syntax I will inevitably start getting bug reports.

The huge benefit to this syntax is you can now do:

`Poison.decode!(json, as: %Person{age: 50})` and it will default the age field to `50`.

**Comment by stevedomin** [comment]
:heart: :yellow_heart: :green_heart: :blue_heart:

**Comment by josevalim** [comment]
@devinus the idea is that, for each field in the map, you would check if it exists in the struct and what is its type? And if it happens to be another struct, you know how to decode it? That sounds good, specially because %Person{} would work out of the box as long as it defaults to an Address. However, how would you do collections? If the collection is a default, it is very likely the collection would be empty and you cannot pass something like `%Person{addresses: %Address{}}` because of dialyzer.

A counter proposal is to use a syntax similar to associations in Ecto:

    Poison.decode!(json, as: Person)
    Poison.decode!(json, as: {Person, addresses: Address, comments: Comment})
    Poison.decode!(json, as: {Person, addresses: {Address, permalink: Permalink}})

You lose the feature for default attributes though.

**Comment by devinus** [comment]
@josevalim Collections are done like this:

```elixir
Poison.decode!(json, as: %Person{addresses: [%Address{}], comments: [%Comment{}]})
```

**Comment by josevalim** [comment]
:+1:

**Comment by stevedomin** [comment]
I was doing some experiments with the feature and I can't get it working with string keys. See the tests below. Am I doing something stupid?

```elixir
# failing test
person = %{"name" => "Devin Torres", "contact" => %{"email" => "devin@torres.com"}}
assert decode(person, as: %Person{contact: %Contact{}}) == %Person{name: "Devin Torres", contact: %Contact{email: "devin@torres.com"}}

  1) test decoding into nested structs (Poison.DecoderTest)
     test/poison/decoder_test.exs:60
     Assertion with == failed
     code: decode(person, as: %Person{contact: %Contact{}}) == %Person{name: "Devin Torres", contact: %Contact{email: "devin@torres.com"}}
     lhs:  %Poison.DecoderTest.Person{address: nil, age: 42, contact: %Poison.DecoderTest.Contact{email: nil, telephone: nil}, name: "Devin Torres"}
     rhs:  %Poison.DecoderTest.Person{address: nil, age: 42, contact: %Poison.DecoderTest.Contact{email: "devin@torres.com", telephone: nil}, name: "Devin Torres"}
     stacktrace:
       test/poison/decoder_test.exs:63

# working test
person = %{"name" => "Devin Torres", "contact" => %{email: "devin@torres.com"}}
assert decode(person, as: %Person{contact: %Contact{}}) == %Person{name: "Devin Torres", contact: %Contact{email: "devin@torres.com"}}
# successful
```

**Comment by devinus** [comment]
@stevedomin That seems like a bug.
