### ISSUE TITLE
Erlang VM crashed when decoding invalid UTF-8 string

### ISSUE THREAD

**Issue by laozhp** [devinus/poison#34]
```elixir
Poison.decode(<<34, 237, 160, 189, 237, 178, 142, 34>>)
```
String in the example is a CESU-8 encoded string, that's not a valid UTF-8 string, but the code crash erlang VM.

**Comment by devinus** [comment]
@laozhp Good find. It looks like I've got an infinite loop somewhere. I'll investigate.
