### ISSUE TITLE
Helpers for writing Poison.Decoder implementations

### ISSUE THREAD

**Issue by padde** [devinus/poison#35]
For decoding nested structs we can use custom Poison.Decoder implementations, but they're not really well documented and can get quite messy when you need to do a lot of conversions. For example:

```elixir
defimpl Poison.Decoder, for: TaskList do
  def decode(task_list, options) do
    Map.update! task_list, :items, fn items ->
      Poison.Decode.decode(items, Keyword.merge(options, as: [TaskItem]))
    end
  end
end
```

I think it's currently a bit too hard to write them correctly, especially given the tiny but fatal difference between `Poison.Decoder` and `Poison.Decode`. Maybe one of those should be renamed  so that they can be differentiated more easily. Anyway, it would be really nice if we could write the above example with a cleaner syntax, such as this:

```elixir
defimpl Poison.Decoder, for: TaskList do
  use Poison.Decoder.Helpers

  decode_nested do
    decode :items, as: [TaskItem]
  end
end
```

Let me know what you think, If you're interested I'd love to give it a go.

**Comment by devinus** [comment]
@padde I'd rather support an API like this:

```elixir
Poison.decode!(json, as: %Person{addresses: [Address]})
```

Lets use https://github.com/devinus/poison/issues/32 to track it.
