### ISSUE TITLE
Performance issue with struct encoding

### ISSUE THREAD

**Issue by jesenko** [devinus/poison#38]
I have encountered some performance issues when generating JSON response in Phoenix framework, encoding Ecto.Model to JSON using poison. To nail down the issue, I added some benchmarks,

    bench "structs (Poison)", [struct: gen_struct] do
      Poison.encode!(struct)
    end

    defmodule TheStruct do
      defstruct name: "John", age: 27
    end

    defp gen_struct do
      1..10 |> Enum.map(&(%TheStruct{name: "John#{&1}", age: &1 }))
    end

Encoding structs appears to be extremely slow, e.g.

    structs (Poison)                           100   19073.38 µs/op

while the same benchmark with `Map` instead of struct

    defp gen_struct do
      1..10 |> Enum.map(&(%{name: "John#{&1}", age: &1 }))
    end
gives orders of magnitude better perf,

    structs (Poison)                         10000   109.68 µs/op

I am total noob as far as elixir is concerned, so I might be doing something totally flawed in the benchmark. The issue is probably not even directly related to the Poison as I have noticed the same performance drop in other Elixir JSON libraries, e.g.

    structs (JSX)                              100   18999.76 µs/op
    structs (Jazz)                             100   19457.10 µs/op

Benchmark for structs can be found in commit 6c6827f9032ac59cec6e29442589cf6a70f06556

Version info:
Elixir 1.0.5
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

**Comment by dazuma** [comment]
+1
I've also encountered this while investigating a performance bottleneck in a Phoenix application that generates JSON responses. I ran a similar benchmark and got similar results: about two orders of magnitude performance difference between a struct and its equivalent map. Erlang/OTP 18 also gives similar results.

**Comment by devinus** [comment]
Unfortunately, I believe this is inherent in Elixir protocols for the `Any` fallback. Maybe @josevalim can shed some light?

**Comment by josevalim** [comment]
@devinus I think we should make Poison derivable and tell people to start deriving the structs. It would also be a great opportunity to support `:only`/`:except`:

    @derive Poison.Encoder
    defstruct ...

    @derive {Poison.Encoder, only: [:name, :age]}
    defstruct ...

And so on. We can't make Any fallbacks any faster.

**Comment by devinus** [comment]
@josevalim How can I implement that?

**Comment by josevalim** [comment]
@devinus Here is an example: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/param.ex

Notice the API slightly changed between 1.0 -> 1.1 (one calls Map, the other calls Any).

**Comment by devinus** [comment]
@josevalim Got it, thanks.

**Comment by devinus** [comment]
This will be part of Poison 2.0. Updates this weekend.

**Comment by josevalim** [comment]
@devinus let me know when you have something ready so I can sanity check. :)

**Comment by devinus** [comment]
I will have a PR ready for this tonight and will merge after @josevalim's much appreciated review! :grin:

**Comment by devinus** [comment]
This is part of Poison 1.5.0. No API changes required, but if you want *super speed* then `@derive [Poison.Encoder]` in your structs.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by tmjoen** [comment]
This is awesome!

**Comment by dazuma** [comment]
Thanks, I just updated to 1.5.0 and tried `@derive [Poison.Encoder]` in my application, and things look great!
