### ISSUE TITLE
[Question] How to pretty print?

### ISSUE THREAD

**Issue by jordi-chacon** [devinus/poison#41]
Hi,

how can I use Poison.encode to pretty print a map?

I have been looking at the source code and I believe this should work, but it doesn't:
```
iex(1)> Poison.encode(%{"a"=>1, "b" => 2}, [pretty: true])    
{:ok, "{\"b\":2,\"a\":1}"}
```

Thank you!

**Comment by devinus** [comment]
`Poison.encode!(data, pretty: true)`

**Comment by KristerV** [comment]
This confusion is still an issue. So PR https://github.com/devinus/poison/pull/193.
