### ISSUE TITLE
[Question] Will Poison support Elixir 1.1.X anytime soon?

### ISSUE THREAD

**Issue by lucca65** [devinus/poison#46]
We depend on Poison, today we are using a fork that only changes the elixir version, so it don't break, do you have any prevision of when `poison` will be updated?

**Comment by devinus** [comment]
@lucca65 Can you post a screenshot of what you're seeing? I can't replicate any warning.

**Comment by devinus** [comment]
@lucca65 https://github.com/devinus/poison/pull/45#issuecomment-145147050
