### ISSUE TITLE
Struct not being encoded

### ISSUE THREAD

**Issue by alirz23** [devinus/poison#48]
Hi,

Thank you for putting this library together.

I am a newbie to elixir I am following an article 
https://robots.thoughtbot.com/testing-a-phoenix-elixir-json-api
when I get to the encoding part

`contact_as_json =
    %Contact{name: "Rambo", phone: "801-555-5555"}
     |> Repo.insert
     |> List.wrap
     |> Poison.encode!`

above throws following error

`** (Poison.EncodeError) unable to encode value: {:ok, %Hawk.Contact{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 4, inserted_at: #Ecto.DateTime<2015-10-09T00:57:37Z>, name: "Rambo", phone: "801-555-5555", updated_at: #Ecto.DateTime<2015-10-09T00:57:37Z>}}`

regards

**Comment by devinus** [comment]
@alirz23 Poison doesn't encode tuples, your value is a tuple. Maybe you want to pipe to  `elem(1)` before piping it to `Poison.encode!`?

**Comment by alirz23** [comment]
if I use Repo.insert! with bang it returns

'%Hawk.Contact{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 26,
 inserted_at: #Ecto.DateTime<2015-10-09T01:28:34Z>, name: "Rambo",
 phone: "801-555-5555", updated_at: #Ecto.DateTime<2015-10-09T01:28:34Z>}'

even that does not get encoded 

`{nil, "contacts"}`

**Comment by devinus** [comment]
What does your encoder look like for a `Hawk.Contact`?

**Comment by alirz23** [comment]
here is the link to the article I am following https://robots.thoughtbot.com/testing-a-phoenix-elixir-json-api

I did not implement the Poison.Encoder protocol in my model

**Comment by devinus** [comment]
I'm not sure. Try contacting the author of the blog post. Poison can definitely encode structs if they're simply structs and there aren't any tuples. I'm willing to bet it's your `__meta__` key. `contacts` looks like your database table name, and that's something that would be seems like it would be stored in `__meta__`.

**Comment by devinus** [comment]
Looks like it's the `__meta__` key: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/schema.ex#L321

**Comment by alirz23** [comment]
If I pull out one single row like so

`Hawk.Repo.get!(Hawk.Contact, 1)`

above returns a struct why is not being encoded

`%Hawk.Contact{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 1,
 inserted_at: #Ecto.DateTime<2015-10-09T00:57:03Z>, name: "Rambo",
 phone: "801-555-5555", updated_at: #Ecto.DateTime<2015-10-09T00:57:03Z>}`

**Comment by alirz23** [comment]
I figured I might as well pipe it through Map.take and just take the fields I need and then pipe it to Poison.encode!

`Hawk.Repo.get!(Hawk.Contact, 1) |> Map.take([:name, :phone]) |> Poison.encode!`

Thank you!

**Comment by alirz23** [comment]
it turns out following changes were pushed out in 0.14.3

"Looks like it's the __meta__ key: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/schema.ex#L321"

**Comment by Mehonoshin** [comment]
Hi, @devinus
Why doesn't poison encode tuples? What if we'll cast them to json array?

**Comment by minhajuddin** [comment]
Adding the following to your project should encode tuples as lists

```elixir
defimpl Poison.Encoder, for: Tuple do
  def encode(tuple, options) do
    tuple
    |> Tuple.to_list
    |> Poison.encode!
  end
end
```

This uses Poison's protocol support.
