### ISSUE TITLE
possible to improve performance?

### ISSUE THREAD

**Issue by mrhooray** [devinus/poison#56]
in the flamegraph of a simple api server, json parsing is apparently the bottleneck, besides reducing the payload, any idea of making this faster?
![screen shot 2016-01-11 at 7 45 18 pm](https://cloud.githubusercontent.com/assets/2237317/12254312/ed72e63c-b89b-11e5-8ce0-ed38228fb0d8.png)

**Comment by devinus** [comment]
You can check out the benchmarks of Poison compared to other JSON libraries. I welcome any ideas to improve performance in the parser, but it is meticulously hand-crafted to be as fast as I can make it right now without some mind blowing insights.

**Comment by nuss-justin** [comment]
@devinus Naive question:

The [number_complete function](https://github.com/devinus/poison/blob/24e4f69589f8adf0399fc18a49690d3d1573fecd/lib/poison/parser.ex#L169) used by number_exp uses binary_to_integer (String.to_integer) and iodata_to_binary (as seen in the image).

Have you tried to use [:erlang.list_to_integer/1](http://www.erlang.org/doc/man/erlang.html#list_to_integer-1) (and [:erlang.list_to_float/1](http://www.erlang.org/doc/man/erlang.html#list_to_float-1) for the float case)? From my understanding of the documentation the :erlang.list_to_(float|integer)/1 functions should give the same result, but could avoid converting to binary first, only to convert directly to an integer/float.

I haven't profiled it myself, but from the image it seems like this could maybe save some time.

**Comment by devinus** [comment]
@nuss-justin Not naive. Every observation is potentially a bump at this point. The list_to_* fuctions require the argument to be a charlist, it can't be an iolist. So we'd have to build a char list rather than an iolist.

**Comment by mrhooray** [comment]
opted in jiffy with about 0.8x improvement
but still thanks for the great work @devinus
