### ISSUE TITLE
Nested struct decoding still doesn't seem to work

### ISSUE THREAD

**Issue by alakra** [devinus/poison#64]
Steps to recreate:

* Pulled the `master` branch (052ad9a9609b33d832b5cf6728cb123b110f2f51)
* Compiled the app with `mix deps.get` and `mix compile`
* Booted up `IEx` like so: `iex -S mix`
* Pasted the following struct (from the `Usage` example in the `README`) into the console:
```
      defmodule Person do
        @derive [Poison.Encoder]
        defstruct [:name, :age]
      end
```
* Pasted the decode call into the console:
```
Poison.decode!(~s({"people": [{"name": "Devin Torres", "age": 27}]}),
  as: %{"people" => [Person]})
```

And got:

```
%{"people" => [%{"age" => 27, "name" => "Devin Torres"}]}
iex(3)>
```

---------------

Seems like this should have been fixed by #61, no?

Thanks ahead of time for looking at this and making this lib! :heart:

**Comment by devinus** [comment]
@alakra Poison no longer supports that syntax. Try `as: %{"people" => [%Person{}]}`

**Comment by alakra** [comment]
Just saw that.  I submitted a PR to update the docs.
