### ISSUE TITLE
FunctionClauseError

### ISSUE THREAD

**Issue by timscott** [devinus/poison#66]
I am a Rails dev just getting started with Elixir. Thanks for your patience.

In a Phoenix app I am fetching a list of objects from MongoDB and rendering as json, like so:

```elixir
def index(conn, _params) do
  mongo = Mongo.connect!
  db = mongo |> Mongo.db("my_db")
  collection = db |> Mongo.Db.collection("my_collection")
  items = collection |> Mongo.Collection.find() |> Enum.to_list
  json conn, items
end
```

I get this error:

```iex
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
        (poison) lib/poison/encoder.ex:127: Poison.Encoder.BitString.chunk_size(<<176, 87, 109, 84, 105, 109, 111, 60, 0, 0, 18>>, nil, 1)
        (poison) lib/poison/encoder.ex:122: Poison.Encoder.BitString.escape/2
        (poison) lib/poison/encoder.ex:84: Poison.Encoder.BitString.encode/2
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:232: anonymous fn/3 in Poison.Encoder.List.encode/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
        (poison) lib/poison.ex:41: Poison.encode!/2
        (phoenix) lib/phoenix/controller.ex:186: Phoenix.Controller.json/2
        (my_app) web/controllers/items_controller.ex:2: MyApp.ItemsController.action/2
        (my_app) web/controllers/items_controller.ex:2: MyApp.ItemsController.phoenix_controller_pipeline/2
        (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (my_app) web/router.ex:1: MyApp.Router.do_call/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (my_app) lib/plug/debugger.ex:93: MyApp.Endpoint."call (overridable 3)"/2
```

```items``` is a list of maps. Each map represents a MongoDB document. Each document has a MongoDB assigned id like this ```_id: ObjectId(56b0576d54696d6f3c000011)```. Some of the values in each document are lists of string and others are lists of maps. Some of values are strings with escaped double quotes in them.

Any idea what might be wrong?

**Comment by ericmj** [comment]
JSON does not support binary data so if you have structs that have binaries (for example ObjectId) you need to implement JSON.Encoder for them and convert the binaries to utf8 encoded strings.

**Comment by devinus** [comment]
Correct, it looks like `<<176, 87, 109, 84, 105, 109, 111, 60, 0, 0, 18>>` is a non utf-8 string.

**Comment by timscott** [comment]
Thanks. In case anyone else encounters this, I solved it by adding this penultimate line:

```elixir
items = for item <- items, do: Map.put item, :_id, to_string(item._id)
```

Being an Elixir newb, I suppose this is not perfectly elegant or idiomatic, but it does what I want.

**Comment by marcosriso** [comment]
Hi there,
I added the line below but it is still not working,

`items = for item <- items, do: Map.put item, :_id, to_string(item._id)`

I get:
key :_id not found in: %{"_id" => #BSON.ObjectId<59e94002a28729527df848c1>

Could you please help me? Thank you!

**Comment by marcosriso** [comment]
Hello, I fixed by adding this in my application.ex in the lib folder

  defimpl Poison.Encoder, for: BSON.ObjectId do
    def encode(id, options) do
      BSON.ObjectId.encode!(id) |> Poison.Encoder.encode(options)
    end
  end
