### ISSUE TITLE
keys: :existing_atoms option

### ISSUE THREAD

**Issue by cryptobird** [devinus/poison#69]
Hey there! 
Usually when I'm dealing with json, it's heavily nested. In elixir, I tend to want to do something like `keys: :atoms`, but then I'm not sanitizing very well. instead of having to write nested loops to change everything to atoms, is there any way we could implement a `keys: :existing_atoms` option?

**Comment by ericmj** [comment]
It's not documented in the API docs but you can pass `keys: :atoms` or `keys: :atoms!`. There are examples in the readme.

**Comment by cryptobird** [comment]
@ericmj would `:atoms!` be for `to_existing_atom`?

**Comment by edgurgel** [comment]
There's an explanation here: https://github.com/devinus/poison#parser

```
Note that keys: :atoms! reuses existing atoms, i.e. if :name was not allocated before the call, you will encounter an argument error message.

You can use the keys: :atoms variant to make sure all atoms are created as needed. However, unless you absolutely know what you're doing, do not do it. Atoms are not garbage-collected, see Erlang Efficiency Guide for more info:
```

**Comment by cryptobird** [comment]
@edgurgel @ericmj Thanks for your help, guys! I can close this issue then :+1:
