### ISSUE TITLE
Correct way to coerce struct fields from strings to other types?

### ISSUE THREAD

**Issue by jordan0day** [devinus/poison#70]
I have a struct like this:
```Elixir
defmodule StreamingBuffer do
  defstruct [:estimatedRows, :estimatedBytes, :oldestEntryTime]

  @type t :: %__MODULE__{
    estimatedRows: non_neg_integer,
    estimatedBytes: non_neg_integer,
    oldestEntryTime: non_neg_integer
  }
end
```

But the API that I'm calling returns each of those fields as strings, not as integers, and Poison decodes the struct with string fields:

```Elixir
x = "{\"estimatedRows\" => \"12\", \"estimatedBytes\" => \"1024\", \"oldestEntryTime\" => \"1\"}"
Poison.decode!(x, as: %StreamingBuffer{})

%StreamingBuffer{estimatedBytes: "1024", estimatedRows: "12",
 oldestEntryTime: "1"}
```
 Is there a good way to tell Poison to decode those fields as integers? Or is the correct approach to write a `Decoder` implementation for each of my structs that have this issue?

As an aside, it seems a little weird to me that the `value` passed in to a custom decoder is an instance of the struct, as opposed to a plain map? I'm sure there are reasons why that I'm missing, but I'd love to have a little more insight into how & why the decodes work this way? I haven't done much with protocols in elixir yet.

**Comment by Qqwy** [comment]
This does not seem like a missing feature of Poison, in my opinion. Rather, the API you are calling is not following the conventions of JSON.

A simple (but maybe not the cleanest) solution you could do, is to iterate over the constructed fields, converting them to integers if `(String.to_integer(field) |> Integer.to_string) == field`. A similar thing can of course also be done with floats.

**Comment by jordan0day** [comment]
Yeah, at the time I wrote this issue I was less familiar with Poison than I am now, so I was hoping maybe I was missing something in the documentation that might cover how to do this.

API-wise, I think writing a decoder for this type and converting from Strings to the correct type for each field is the right way to go. I can't picture a way to implement this more generically in the Poison API without things getting fairly ugly.
