### ISSUE TITLE
Error when parsing strings with embedded/escaped double quotes

### ISSUE THREAD

**Issue by freizeit** [devinus/poison#71]
Json parser does not deal with strings that contain embedded/escaped double quotes correctly i.e. it

- bombs out when single backslashes are used
- works with two backslashes

I tried pasting examples here but github markdown gave me hell, so, here it goes: https://paste.ubuntu.com/15414010/

**Comment by devinus** [comment]
Put `'{ "k": "this breaks -> \"a\"" }'` into your terminal, you'll see why.

**Comment by freizeit** [comment]
I apologise if I am missing something entirely obvious but I do not get it..

**Comment by freizeit** [comment]
Also top of page 4 of the ECMA 404 spec states:

```\" represents the quotation mark character (U+0022).```

**Comment by devinus** [comment]
@freizeit You are escaping `"` in *Elixir*, but not as a literal `\"` in the *JSON string*.
