### ISSUE TITLE
Implement Poison for Elixir v1.3 calendar types

### ISSUE THREAD

**Issue by josevalim** [devinus/poison#77]
Hi @devinus,

Could you please implement Poison.Encoder for Elixir v1.3 calendar types and make a new release?

Elixir protocol implementation does not actually check if the thing you are implementing for exists at the moment of implementation, this means you can implement the protocols and be backwards incompatible. Here is how we implemented those for Phoenix.HTML.Safe protocol:

https://github.com/phoenixframework/phoenix_html/commit/d78a082aed6220bb0454a14203f48ee1274b43e6

I think the only difference is that you will want to invoke `to_iso8601` on every type instead of `to_string` invoked in the link above.

Thank you! :heart:

**Comment by josevalim** [comment]
Btw, the reason I am asking for a new release is because I will need it in Ecto. ;D

**Comment by lucidstack** [comment]
I think this can now be closed, @josevalim @devinus? 😁
