### ISSUE TITLE
Decode 'null' to struct

### ISSUE THREAD

**Issue by ejmuylaert** [devinus/poison#83]
At the moment, this is the behaviour from Poison when creating a struct from the JSON "null"
```
defmodule MyStruct do
  defstruct one: "", two: ""
end

{:ok, nil} = Poison.decode("null", as: %MyStruct{})
```
I would have expected:
```
{:ok,  {:ok, %MyStruct{one: "", two: ""}} = Poison.decode("null", as: %MyStruct{})
```
or even better, Poison will generate an error like:
```
{:error, {:invalid, "expected an object, got null"} = Poison.decode("null", as: %MyStruct{})
```

Please let me know what the expected behaviour is. Then I will try to create a pull request.

**Comment by ericmj** [comment]
I would say the current behaviour is the expected behaviour. It's consistent with how `null`/`nil` works and is used in programming languages.

**Comment by ejmuylaert** [comment]
@ericmj You're argument is sound. I close the issue.
