### ISSUE TITLE
Decoding arrays with numeric elements fails

### ISSUE THREAD

**Issue by ovx** [devinus/poison#86]
Hi, there is some strange decoding behaviour when decoding a simple array with numeric elements that start with '1':

```
>Poison.decode("[1]")
{:ok, [1]}
>Poison.decode("[12]")
{:ok, ['\f']}
>Poison.decode("[123]")
{:ok, ['{']}
>Poison.decode("[1234]")
{:ok, [1234]}
>Poison.decode("[12, 12, 12]")
{:ok, ['\f', '\f', '\f']}
>Poison.decode("[22, 22, 22]")
{:ok, [22, 22, 22]}
```

Using Poison 2.2.0

**Comment by devinus** [comment]
This has to do with the way Elixir represents integers as characters. It's not a bug.
