### ISSUE TITLE
ArgumentError in Poison.Parser.string_escape/2, char range `\\ud800` to `\\udfff`

### ISSUE THREAD

**Issue by jockee** [devinus/poison#88]
ArgumentError on decode:

```elixir
Poison.decode("{\"s\": \"\\ud83d\"}")
```

    ** (ArgumentError) argument error
        (poison) lib/poison/parser.ex:229: Poison.Parser.string_escape/2
        (poison) lib/poison/parser.ex:78: Poison.Parser.object_pairs/3
        (poison) lib/poison/parser.ex:36: Poison.Parser.parse/2
        (poison) lib/poison.ex:69: Poison.decode/2

Poison 2.2.0

**Comment by devinus** [comment]
That range is for unicode surrogate pairs. Alone it is invalid.

**Comment by ericmj** [comment]
@devinus Should it raise? Shouldn't it return an error tuple?

**Comment by devinus** [comment]
@ericmj It's an argument error because of guards. Other things would return an argument error too like passing it a number or something. Where do you draw a line? Unsure.

**Comment by jockee** [comment]
Not interested in adding an option for it to return an empty string in these cases? Failing "safely".

**Comment by alex88** [comment]
We get a JSON from an external service like this:
```
{"summary":"\uD83D\uDE02\uD83D\uDE02\uD83D\uDE02\uD83D\uDE02\uD83D\uDE02\uD83D\uDE02\uD83D..."}
```
and poison crashes, maybe it should just not throw argument error but json decoding error?

**Comment by net** [comment]
@alex88 Poison will return a `Poison.ParseError` instead of raising on master.

**Comment by alex88** [comment]
@net yeah just figured that out, thanks!
