### ISSUE TITLE
Poison.Parser.parse failure on weird surrogate pair

### ISSUE THREAD

**Issue by vorce** [devinus/poison#89]
I have some json data that may contain some wonky surrogate pairs. `jq` reports this for it:
`parse error: Invalid \uXXXX\uXXXX surrogate pair escape at line L, column C`

Here's how poison handles the same:

    iex(3)> Poison.Parser.parse("{\"field\":\"\\uD83C\"}")
    ** (ArgumentError) argument error
        lib/poison/parser.ex:229: Poison.Parser.string_escape/2
        lib/poison/parser.ex:78: Poison.Parser.object_pairs/3
        lib/poison/parser.ex:36: Poison.Parser.parse/2

Cryptic error aside, is there any way I could instruct poison to ignore these errors? Or tell it to not parse some parts? Do you have any suggestions on how to deal with this sort of data?

I'm using 2.2.0 btw.

Thanks a bunch and kudos for an awesome library. ❤️ 

Edit: Hmm for some reason http://jsonlint.com/ can handle the same input...

**Comment by devinus** [comment]
@vorce You should scrub the data before hand, removing invalid surrogate pairs. I doubt Poison is ever going to try to parse invalid JSON and invalid UTF8 surrogate pairs is invalid JSON. Maybe if I saw a proposal on how to handle invalid JSON in general I would consider it.

**Comment by vorce** [comment]
Hm I think I made a mistake in my first comment. `jq` does seem to accept it:
`echo '{"field": "\uD83C"}' | jq .
{
  "field": "�"
}`

Maybe it's not an invalid surrogate pair? 😕 

And all other json parsers/validators seem to accept it that I have tried so far.

**Comment by devinus** [comment]
You can see why this happens by running `<<String.to_integer("D83C", 16) :: utf8>>`.

It's just not a valid unicode character by itself.

**Comment by vorce** [comment]
Right. I ended up substituting such stuff with � using a regex and some code.
