### ISSUE TITLE
Poison.decode very slow for JSON documents with large strings

### ISSUE THREAD

**Issue by samginn** [devinus/poison#90]
When trying to decode a 6MB JSON document (essentially an array of very long strings), Poison decodes unacceptably slow. The JSON document has 6,045,531 characters in it totally. I ran exprof on this simple code:

```elixir
{:ok, string} = File.read "test.json"
profile do
  Poison.decode!(string)
end
```

And the result was:
```
FUNCTION                                        CALLS        %     TIME  [uS / CALLS]
--------                                        -----  -------     ----  [----------]
erlang:send/2                                       1     0.00        0  [      0.00]
'Elixir.Poison.Decode':decode/2                     1     0.00        1  [      1.00]
'Elixir.Poison':'decode!'/2                         1     0.00        1  [      1.00]
'Elixir.Poison':'decode!'/1                         1     0.00        2  [      2.00]
'Elixir.Poison.Parser':'parse!'/2                   1     0.00        3  [      3.00]
'Elixir.Access':get/3                               2     0.00        3  [      1.50]
lists:keyfind/3                                     2     0.00        3  [      1.50]
'Elixir.Poison.Parser':parse/2                      1     0.00        4  [      4.00]
'Elixir.Access':fetch/2                             2     0.00        5  [      2.50]
'Elixir.Access':get/2                               2     0.00        5  [      2.50]
'Elixir.MyApp.Document':'-get/1-fun-0-'/1         1     0.00        6  [      6.00]
lists:reverse/2                                    43     0.00       38  [      0.88]
maps:from_list/1                                  102     0.00      114  [      1.12]
'Elixir.Poison.Parser':object_pairs/3             205     0.00      202  [      0.99]
lists:reverse/1                                   102     0.00      207  [      2.03]
'Elixir.Poison.Parser':number_frac/2              244     0.00      223  [      0.91]
'Elixir.Poison.Parser':number_exp/3               244     0.00      232  [      0.95]
erlang:binary_to_integer/1                        244     0.00      234  [      0.96]
'Elixir.Poison.Parser':number_start/1             244     0.00      235  [      0.96]
'Elixir.Poison.Parser':number_int/2               244     0.00      237  [      0.97]
'Elixir.Poison.Parser':array_values/3             341     0.01      320  [      0.94]
'Elixir.Poison.Parser':object_name/2              205     0.01      357  [      1.74]
'Elixir.Poison.Parser':number_complete/2          244     0.01      413  [      1.69]
'Elixir.Poison.Parser':number_digits/1            244     0.01      435  [      1.78]
'Elixir.Poison.Parser':value/2                    547     0.02     1010  [      1.85]
'Elixir.Poison.Parser':number_digits_count/2      960     0.02     1062  [      1.11]
'Elixir.Poison.Parser':skip_whitespace/1         1504     0.05     2664  [      1.77]
erlang:iolist_to_binary/1                         549     0.09     5206  [      9.48]
'Elixir.Poison.Parser':string_escape/2          21120     0.38    20854  [      0.99]
'Elixir.Poison.Parser':string_continue/2        32242     0.55    30085  [      0.93]
'Elixir.Poison.Parser':string_chunk_size/2    6011582    98.83  5440137  [      0.90]
--------------------------------------------  -------  -------  -------  [----------]
Total:                                        6071225  100.00%  5504298  [      0.91]
```

Not sure why there are so many calls to Elixir.Poison.Parser:string_chunk_size/2, but the number of calls is roughly equivalent to the number of characters in the document.

**Comment by ericmj** [comment]
How slow is "unacceptably slow"? Can you give us numbers and what kind of machine you are running it on? Also please provide sample data that we can reproduce with.

**Comment by samginn** [comment]
I am running it on a 2015 Macbook Pro (16 GB RAM, 2.5 GHz). 

So, to parse this [8.1 MB JSON file](https://gist.github.com/samginn/4bf849dbd3b6ddba87ec78dbbd7345c9), exprof shows that it takes 6.5 seconds.

**Comment by ericmj** [comment]
Keep in mind that profiling adds significant overhead. On my 2013 macbook I parse the json in 200ms which I think is OK.

**Comment by devinus** [comment]
I'm not sure about *unacceptably* slow, but I'm definitely not happy with the performance of our string parsing which had to become crazy complex to handle everything.

**Comment by samginn** [comment]
You are right, it parses in about 150ms for me without using exprof (measured with Benchee this time). I originally ran into the slowness when using rethinkdb_elixir, where a query for a very large document was taking >5s to complete (while using the python rethinkdb library on the same rethinkdb server, it was near instantaneous). So, I ran exprof on the code and found that the majority of the call (98%) was in Poison. I then ran exprof on Poison standalone and found it took a comparably long time (~5s) not knowing that exprof itself would be the cause of the slowdown there. So, it is probably a problem with the rethinkdb_elixir library then.

Thanks, anyways!

**Comment by devinus** [comment]
@samginn If you could give me the document as a JSON file I could add it to the benchmarks.

**Comment by samginn** [comment]
@devinus Does this work? https://gist.github.com/samginn/4bf849dbd3b6ddba87ec78dbbd7345c9

**Comment by devinus** [comment]
@samginn Yep, thanks.

**Comment by devinus** [comment]
These are my benchmarks:

```
## ParserBench
benchmark name             iterations   average time
Issue 90 (jiffy)                  100   16670.12 µs/op
Issue 90 (Poison)                  50   43648.56 µs/op
Issue 90 (JSX)                     10   138894.80 µs/op
Issue 90 (JSON)                     1   2043913.00 µs/op
```

It looks like Poison is only 2.6x slower than jiffy. I'm not sure if that's unacceptably slow, but we could investigate more performance improvements around string parsing.
