### ISSUE TITLE
Invalid output when mixing strings and atoms

### ISSUE THREAD

**Issue by tonyarkles** [devinus/poison#91]
This was my mistake, but I got highly unexpected behaviour out of Poison when it happened. I have a dictionary that is a mixture of atoms and strings for keys, and in the output there is a duplicated key, which is not valid JSON.

Minimal test case:

```
iex(12)> Poison.encode! %{ :foo => "bar", "foo" => "baz" }
"{\"foo\":\"baz\",\"foo\":\"bar\"}"
```

The result is that the other side of the HTTP endpoint would ambiguously parse the output. Very tricky to debug.

**Comment by BennyHallett** [comment]
Interesting issue.

I've had a look and made a small change - will put a PR in shortly. I've made the assumption that Poison shouldn't make the decision about which of those two entries are the right one to end up in the final JSON - and it raises an error.

Interestingly it seems the same problem exists in Ruby


```
pry(main)> { :a => "a", "a" => "A" }.to_json
=> "{\"a\":\"a\",\"a\":\"A\"}"
```

I also checked my browser (Chrome) and it chooses the last value that is entered when an object has the same key multiple times.

Do you think failing when we have multiple matching keys is the right way to go about this @devinus ?

**Comment by tonyarkles** [comment]
@BennyHallett thanks for looking into it! It seems that that ordering isn't (last value entered) predictable on bigger maps. I was doing a large ```Map.merge(default_values, actual_values)``` and it would be pretty unpredictable what would happen.

The solution I ended up taking was to explicitly normalize all of my keys to strings before doing the merge. Worked great for me, but doesn't solve the general case problem. My normalization function did fail when there were multiple matching keys :)

**Comment by BennyHallett** [comment]
No worries. My solution was to just fail - I'm not sure it's Poison's responsibility to decide which key the programmer wants to include

**Comment by BennyHallett** [comment]
I've got a fix for this but I'm not entirely happy with it - the benchmarks show a jump in processing time for maps from around 20 µs/op to around 40 µs/op. While 20 µs is almost nothing, I don't think a 100% increase in processing time is a good thing.

The change makes the encoding fail when we detect duplicate keys. It does this by normalising the keys into an array, running Enum.uniq on it, and then comparing the length of that to the length of the keys in the original map.

Can anyone think of a more efficient way of doing this?

**Comment by tonyarkles** [comment]
Hmmmm, my workaround just straight up normalized to all string keys and failed if it came across a dupe. Not sure if it's faster or slower than what you've got:

```
  def normalize_map(m) do
    {r, dupes} = Enum.reduce(Map.to_list(m), {%{}, false}, fn({k,v}, state) ->
      {acc, dupes} = state
      key = cond do
        is_atom(k) -> Atom.to_string(k)
        true -> k
      end
      { Map.put(acc, key, v),
        dupes || Map.has_key?(acc, key)
      }
    end)
    case dupes do
      false -> {:ok, r}
      true -> {:error, :duplicate_key}
    end
  end
```

**Comment by BennyHallett** [comment]
@tonyarkles Thanks for that - gave me some ideas.

Unfortunately it's still slow - I made a PR for what I've got, hopefully someone has some ideas. One that I've added is to make the key validation optional, so that developers can trade off between speed and correctness.

Interested to see what @devinus and yourself think.

**Comment by tonyarkles** [comment]
You guys rock. Thanks!
