### ISSUE TITLE
UUID interpreted as float

### ISSUE THREAD

**Issue by coryodaniel** [devinus/poison#99]
This probably isn't a use case anyone else is dealing with, but I was looping through some values and decoding and one happened to be a UUID and it was interpreted as a float, which hung up `:erlang.binary_to_float/1`

```elixir
Poison.decode("322e325b-08a0-4721-9d55-cb062e5f25f8")
```

```bash
** (ArgumentError) argument error
             :erlang.binary_to_float("322.0e325")
    (poison) lib/poison/parser.ex:173: Poison.Parser.number_complete/2
    (poison) lib/poison/parser.ex:165: Poison.Parser.number_exp_continue/2
    (poison) lib/poison/parser.ex:36: Poison.Parser.parse/2
    (poison) lib/poison.ex:69: Poison.decode/2
```

**Comment by ericmj** [comment]
@coryodaniel Was the UUID wrapped in a JSON string? What you posted above is not valid JSON.

**Comment by coryodaniel** [comment]
No it wasn't. I'm unfortunately parsing something that occasionally has weird values as it's "json" and was hoping that since Poison parsed strings 'Poison.decode("hello")' correctly it would work on this. 

I ended up putting a big "try" around it and just keeping the original string of decoding fails. 

Sorry for the lame issue!

**Comment by ericmj** [comment]
Poison won't actually parse this: `Poison.decode("hello")`.

**Comment by coryodaniel** [comment]
Hah, sorry I had some strings coming through as `Poison.decode("\"hello\"")` Like I said originally, weird use case, parsing odd stuff. 

Poison has been great for my valid JSON :D 
Thanks!

**Comment by sdball** [comment]
I've run into this as well with nested decoding of JSON including alphanumeric tokens. Here's a snippet detailing the surprising behavior if the string happens to be interpreted as a number:

```
> Poison.decode("7E40")
{:ok, 7.0e40}

> Poison.decode("7E40ff")
{:error, {:invalid, "f", 4}}

> Poison.decode("7E407")
** (ArgumentError) argument error
    :erlang.binary_to_float("7.0e407")
    lib/poison/parser.ex:194: Poison.Parser.number_complete/2
    lib/poison/parser.ex:186: Poison.Parser.number_exp_continue/3
    lib/poison/parser.ex:37: Poison.Parser.parse/2
    lib/poison.ex:69: Poison.decode/2

> Poison.decode("7E407ff")
** (ArgumentError) argument error
    :erlang.binary_to_float("7.0e407")
    lib/poison/parser.ex:194: Poison.Parser.number_complete/2
    lib/poison/parser.ex:186: Poison.Parser.number_exp_continue/3
    lib/poison/parser.ex:37: Poison.Parser.parse/2
    lib/poison.ex:69: Poison.decode/2
```

The problem seems to be that the interpreted number is so huge that it's breaking `:erlang.binary_to_float`.

**Comment by ericmj** [comment]
@sdball Poison is raising, as is expected here, because we cannot decode numbers that are not valid floats or integers.

**Comment by sdball** [comment]
I'd have expected a raise here if I were calling `decode!` but not from `decode`. Instead of an exception I expect an error tuple.

```elixir
> Poison.decode("1.23")
{:ok, 1.23}

> Poison.decode("1.23.6")
{:error, {:invalid, ".", 4}}
```

If `decode` is expected to raise exceptions in some cases should we update its spec to show that?

```
@spec decode(iodata, Keyword.t) :: {:ok, Parser.t} | {:error, :invalid}
  | {:error, {:invalid, String.t}}
```

https://github.com/devinus/poison/blob/317f449d2fc2c2bd624f2f23c8efae4ce1d0580d/lib/poison.ex#L66-L67
